server:
  port: 8762

spring:
  application:
    name: mbti-service
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mbti-app-db?useSSL=false&serverTimezone=UTC
    sername: root
    password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

twilio:
  accountSid: "AC3e5d10c0354c6b3299b8ac74f2896799"
  authToken: "4360baa1218c0820ebae0b75adb0e89f"
  phoneNumber: "+13613209144"




